### ISSUE TITLE
Week 5 Typos

### ISSUE THREAD

**Issue by sean-schaefer** [azbones/big_data#10]
- In supervised learning, a training dataset is being (missing _used_) to build a model...
- Often after developing the model, a seperate (should be _separate_)...
- ...read them into a pandas dataframe for convienence (should be _convenience_)...
- We are again going to create a synthentic (should be _synthetic_) dataset
- ...show the percentage of varaince (should be _variance_)...
- # Computer (should be _Compute_) average min distance
- ...how could you improve your model at making predicitons (should be _predictions_)?

Also, this same statement occurs twice, both at the beginning of the supervised and unsupervised sections:

_One way to subdivide the machine learning domain is by supervised or unsupervised learning._

**Comment by azbones** [comment]
fixed with several others in week 5
