### ISSUE TITLE
Week 6 Issues

### ISSUE THREAD

**Issue by sean-schaefer** [azbones/big_data#12]
- There are a couple of places local filepaths are hardcoded. I believe we can make these relative, or add a note for them to change to their local paths.
- I did not have ipyparallel as part of my Anaconda install and didn't see it as part of the setup. We may need to add that and add a version check.
- Sum of noun phrase counts _in_ (should be _is_) {}’
- In read_texts_parallel, we do not need the f.close as the closing is handled by the context manager.

**Comment by azbones** [comment]
-fixed points 3 and 4

-yea, we can make them relative, i haven't cleaned this one up yet

-I am going to try installing pyparallel tomorrow on my windows machine just to make sure it still works.  I think i pip installed it rather than conda...

**Comment by sean-schaefer** [comment]
Seems like these are all handled @azbones? Can be closed?

**Comment by azbones** [comment]
yes, closed.
